# Generated by Django 5.1 on 2024-08-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="distances",
        ),
        migrations.AddField(
            model_name="event",
            name="distances",
            field=models.ManyToManyField(to="event.distance"),
        ),
    ]
