# Generated by Django 5.1 on 2024-08-09 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_result_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventregistration",
            old_name="user",
            new_name="runner",
        ),
        migrations.RemoveField(
            model_name="result",
            name="event",
        ),
        migrations.RemoveField(
            model_name="result",
            name="runner",
        ),
        migrations.AddField(
            model_name="result",
            name="event_registration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="event.eventregistration",
            ),
        ),
    ]
