# Generated by Django 5.1 on 2024-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_result_event_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
