# Generated by Django 5.1 on 2024-08-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_alter_eventregistration_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="distance",
            field=models.IntegerField(),
        ),
    ]
